# Generated by Django 5.1.3 on 2024-12-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=100)),
                ('result', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordCount', models.IntegerField(max_length=100)),
                ('numCount', models.IntegerField(max_length=100)),
                ('wordArr', models.CharField(max_length=500)),
                ('numArr', models.CharField(max_length=500)),
            ],
        ),
    ]
