image: python:3.13.3-alpine3.20

before_script:
  - pip install -r requirements-dev.txt

stages:
  - style
  - test
  - coverage
  - documentation

pylint:
  stage: style
  script:
    - pylint --fail-under=6 --ignore-paths="docs/*" **/*.py 
    - echo "Pylint complete."
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days

pycodestyle:
    stage: style
    script:
        - pycodestyle --max-line-length=120 main.py
        - echo "Pycodestyle complete."
    artifacts:
        untracked: false
        when: on_failure
        expire_in: 30 days

unittest:
    stage: test
    script:
        - python -m unittest tests.py
    artifacts:
        untracked: false
        when: on_failure
        expire_in: 30 days

coverage:
  stage: coverage
  script:
    - echo "Generating coverage report"
    - coverage run -m unittest tests.py
    - coverage report -m
    - coverage html
  artifacts:
    paths:
      - htmlcov/
    expire_in: 30 days
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

sphinx:
  stage: documentation
  script:
    - apk add --no-cache make
    - echo "Building documentation with Sphinx..."
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/
    expire_in: 30 days
